### ISSUE TITLE
Scheduled channel start error

### ISSUE THREAD

**Issue by Monkhsukh** [gerazo/pipert#3]
**Test code**

```
TEST(SchedulerTest, ChannelCreation) {
    pipert::Scheduler sch(1);

    Printer p;
    pipert::ScheduledChannel<Human> sc = sch.CreateScheduledChannel<Human>("ScheduledChannel", 2, nullptr, std::bind(&Printer::Print, &p, std::placeholders::_1));

    EXPECT_EQ(sc.GetCapacity(), 2);
    EXPECT_EQ(sc.GetPacketSize(), sizeof(pipert::Packet<Human>));
    EXPECT_EQ(sc.GetName(), "ScheduledChannel");

    sch.Start();
}
```

**Test log**
pipert_bbtest: ../src/SchedulerImpl.cpp:39: void pipert::SchedulerImpl::UnregisterChannel(pipert::ChannelImpl*): Assertion `!running_.load(std::memory_order_acquire)' failed.

**Comment by martinb214** [comment]
The problem here is not completely in the Start method. In this implementation your test ends right after calling sch.Start() which means previously created objects' destructors are called. ChannelImpl class's destructor calls UnregisterChannel method, which contains an assertion (in debug build) to check scheduler's running state (which can be true because of the previously called Start method) and you can see this in your error message.

**Comment by Monkhsukh** [comment]
Thanks, Yes, you're right, Here I did not call Stop function.
