### ISSUE TITLE
Less significant problem: Scheduler

### ISSUE THREAD

**Issue by Monkhsukh** [gerazo/pipert#4]
if the scheduler started already and then I call function start again, it gives an error.

```
sch1.Start();
sch1.Start();
EXPECT_EQ(sch1.IsRunning(), true);
// Assertion `!running_.load(std::memory_order_acquire)' failed.
```

**Comment by gerazo** [comment]
Guys, we have multiple options here:
 - The current implementation tells the debugging programmer that you are using the system wrong. (calling Strart on an alread running system) This is only done in debug, so only programmer gets it, it will not slow down anything in release.
 - We do give some kind of explicit error back. The question is what should it be? (I do not like this idea as it is not a normal usage anyway, so why to put it into the API.)
 - We do silent avoidance of the problem, like branching and not doing anything on running. This solves the problem but it will not reveal the potential developer problem (calling start was maybe not intentional).
 - Maybe using assert and also avoidance can be a good combination... mainly because we will not call Start frequently, so it will not slow things down.
WDYT?

**Comment by Monkhsukh** [comment]
In advance, I am asking it in case someone calls start function twice intentionally. But using assert and avoidance can be good practice for sure.

**Comment by gerazo** [comment]
We can do avoidance if we want.

**Comment by gerazo** [comment]
Ok, we will put this case into the documentation to clarify.
