### ISSUE TITLE
Measurement Module Concept (code and architectural change)

### ISSUE THREAD

**Issue by baselqyqony** [gerazo/pipert#6]
check needed change in system in order to add new classes which hold user setting for custom define measurement to be measured in the code  , runtime workflow to process those measurement and output generation format

**Comment by gerazo** [comment]
So far what seems to be clear:
 - Use UDP for transmitting logs to the analyzer (even if it will be the localhost most of the time)
 - Use a separate, dedicated thread to do UDP comm and log serialization + putting together buffer to be sent
 - We log in binary format
 - We need general API and configuration for the monitoring subsystem
 - We need to let the user log own stuff besides the default, framework supplied data
 - The framework logs Packet state changes in all Channels by default.
 - We need to support the analyzer in mapping up the pipeline by logging IDs besides names (thread IDs included)

Open questions:
 - What should be the log format?
 - Do we really want to log everything directly (too much data)? Can we do some lightweight aggregation on the library side (one message for all Packet state changes per Channel... or one aggregated message on averages somehow)?

**Comment by baselqyqony** [comment]
thank you very much ,
and I would like to ask  ,if the UDP transmission is the same as creating socket server  so we can forward logs to it

- for the second point in  open questions I have an Idea so that we make lists of states instead of one value variable  in the measurement profile and sending may occur only in case of dropping in some channel or in case we reached end channel

**Comment by gerazo** [comment]
@baselqyqony I meant UDP network communication. So not Unix sockets and also not TCP network communication. The reason behind this is that what if UDP looses a packet? Nothing, as the analyzer will still have lots of data to analyse... but our delay con be lower with this.

On the 2nd point, you are completely right. I think the approach should be to
 - find out what data we would log individually
 - find out how to aggregate this data (or what parts can be aggregated). This will change the logged format as well. Aggregating values into min/avg/max is easy (and fast, happens without extra memory). However aggregating for example who is the sender object is more difficult (currently I am thinking on this).

Anyway, what is surely needed is a utility which can identify the currently running thread in the system and whether this is ours or not. I plan to implement it very soon.

**Comment by gerazo** [comment]
The bare information on what to log naively is:

- what happened: event type
- how it happened: event value
- on what data: packet ID = packet timestamp
- when: current timestamp
- where: channel name or node name
- by who: thread id

This gives connections between nodes (via thread id, connection can be made between object doing transformation and object getting the newly created packet through acquire). Current timestamp always tells the relative time of data inside the pipeline compared to packet id timestamp. The name of the object and the event type identifies the exact location in code quite weill practically.
What do you think? Is there anything more?
If no, this format can be the basis of any aggregation. (One already implemented is aggregating different event types and current times to the very same packet/channel instance. This is possible because we did not record threadid and we basically represented value 1 in these cases as an event value.)

**Comment by BenBlaise** [comment]
So, seeing that this is the next larger area of development to work on, I went ahead and tried to make sense of all the information that was written down and mentioned here and there over the past few weeks. This is just my interpretation, it consists of a proposed format for aggregated logging and some questions that I hope will advance discussion on the issues we still need to think through thoroughly.

## Format fields

For now, I tried to go along with aggregating statistics related to events.

### 1. Event type

Right now, the 3 useful event types to log would be packet acquisition/push/release.

### 2. Event timings

This consists of the minimum/average/maximum time of the length of each event associated with a *specific* event type.

The meaning of this field would change per event:
- Acquire: represents the length of time the packet took to be filled with data, which starts with the acquisition of the packet and ends with pushing the packet onto a channel.
- Push: represents the length of time the packet spent waiting in the queue to be processed, which starts with the submission of a packet using a push to a queue, and ends with the execution of processing on the packet.
- Release: represents the length of time taken to execute transformation on a packet, which starts with the execution of processing on a packet.

Notice that the first two fields represent timeframes that start with their event types, and only the last one contains a timeframe that ends with its event type. (This should not be a problem with aggregated data, right?)

### 3. Location

This contains either the channel name or the node name where the event originated from. In the case of acquisition, the two would be different. Any thoughts on this?

If we decide to keep with channel names, this field would contain the channel name that the aggregated packets belong to during/after the event. In the case of acquiring a packet, the executed code already has all the context it needs to determine the channel the data was coming from and going to. So, if we add a second field to this, we can map out channel to channel packet motions.

However, what happens in the case when a channel can receive data from multiple channels, how would we aggregate the value of the second field that gives the connection?

### 4. Aggregation counter

How many events of the type does the aggregated data chunk represent.

### 5. Aggregation timeframe

The length of time over which this aggregation chunk was collected.

## Questions

How would it help us to know the thread IDs, and how would we map out connections in the pipeline using them, especially in an aggregated way? Any ideas on how this could be implemented, specifically? The best idea I have right now about it would be to aggregate data into a channel-channel or node-node 2D acquisition/flow counter matrix, and to send the data inside it periodically to the log analyzer, instead of trying to figure it out in some tricky way from event logs alone.

In the previous proposition, what is the purpose of the 'event value' field, exactly?

Any ideas on how the calculation of timeframes beloning to different event types would be calculated?

## Important note

I've tried to build this format in a way that there are no overhead added to packets at all, and aggregation is connected to the respective channels. This might be different from the original idea, but I think at some point, we need to be able to decide whether we want to approach this from the packet side, add overhead to each packet, then aggregate data from the data that exists inside each packet, or to approach it from the channel side, where information only originates from the flow of control, and no data is recorded inside packets. What are your thoughts on this separation? Which one should we go forward with in the future?

**Comment by gerazo** [comment]
### Event Type and Timings
Originally, we had acquire, push, execute and release. But I realize that it is a question what are the most important times of all this. We have some options. Do we want to record
 - total time from pipeline start until event happens to packet
 - time interval while the event is happening

This is a matter of interpretation. I think that we should focus on a solution where
 - bottlenecks in the system can be found by the analyzer tool
 - the total delay can be monitored (we can skip some interprocess waiting if we only measure code runtime, however, this can be a con as well)

It would be good to find a solution which handles user custom measurements and the built-in stuff the same way. It also makes sense because in case of execution, release can happen sooner than the return of the executor function (which will be the transformation time). However, none of these matter because the data can go to the next channel on an acquire and push call from the transformation function. These calls can happen earlier than a release but can also happen later. This is why interval measurements and registering where are we on the packets timeline can be different.

### Location
You are right. Only the connection between senders and receivers matter besides being able to find the place of event in the code (which can work on the ID or something). My suggestion for the technicalities: We should use a thread_local variable inside the thread. The scheduler will put the channel ID into it when the thread calls Execute on the channel. This way, whatever acquire method is called, by reading out the ID from this thread_local variable, we will know the ID of the sender object. This is why we have to do it on the receiver side (in acquire or push). This thread_local variable can be added to the ThreadId class as a payload next to the autotagged value (which is there to detect if a thread is not our, but coming from the outside... in case of pipeline entrance when the user puts data into the 1st channel).

### Aggregations
I was thinking on this. Probably to be perfectly universal, we should unite the mentioned values and only have a value which is aggregated (not having a separate aggregated time as well). So the user always logs a value, it is counted (how many times we got log data), how long the logs were aggregated, min, max, avg. And the built-in functions can always use currenttime-packettime as this value. This way, the user does what he/she likes, we can however decide where to log what as a built-in feature. See above! Again, we should think through how can we map up the pipeline timings the easiest way.

Based on all this, I think that going we the Channel based log approach is better as the Packet based one would only be useful for the built-in events, not the user ones.

**Comment by BenBlaise** [comment]
### Event timings

On event timings: I think we should do both. Notice that the three time intervals I've laid out correspond exactly to the four time points you mentioned. Acquire to push, push to execute, and execute to release. Maybe it would make sense to associate the three intervals with the three interval endpoints (push, execute, release), and to log only at these points, but log both the total time and the local delta-time together. Would this make sense?

Originally, I went with thinking about these time deltas because I believe they would be very efficient (even when aggregated) at showing how much time packets spent in a certain channel of a pipeline. For the sake of completeness, we could also log the aggregated (min/max/avg) value of how long the packets going through the channel have spent in the pipeline. This would not be fully representative, especially if some packets are routed with feedback loops, but would give a good general idea.

In the same way, the total delay could be monitored somehow at the exit point of the pipeline using the aggregation of the total amount of time packets have spent travelling the pipeline before arriving at the exit point.

### Measurement points

I thought about it a bit, and maybe I see what you mean. If I interpreted it right, the problem is that measuring something like the runtime of the executor function does not really coincide with the same packet getting pushed to the next channel in the pipeline. So if we had a theoretically perfectly measurable machine, if we summed up the times a packet spent in all the channels we would get a different value than the time it took to traverse the entire pipeline.

Maybe we need to accept that these are simply to separate things at the moment, and will exist as such until we decide to join them together more tightly (which is probably unnecessary, as it would disturb the architecture a bit). If we leave it as it is, we just need to decide what do we want to measure, really. I think the problem also lies in the fact that pushing a packet in the executor function onto the next stage actually makes a different packet, that is slightly disconnected from the one that is still under execution. Maybe if we don't want to measure the runtime of the executor function (which might be fine), we should look for a connection there.

### User-defined measurements

How would the user measure anything? What kind of things could they measure? Would it be aggregated at all? Should this be separate from the built-in measurements? If not, how are we going to merge them together?

I'm asking all of this because I don't see how we would do user measurements yet. If there is a meaningful difference between the two kinds of measurements, we probably can't measure them together. If they are similar enough or constrained in the same ways, we might get away with doing them in the same way. But, then again, how..?

### Location

If we want to measure which threads worked on which channels, it would absolutely make sense to do it this way. This could tell us the ratio of the work performed by different threads in a single channel.

However, the question of how we collect and send flow information over to the analyzer is still open, I think. Do we want to complicate the event logs with it, and let the analyzer figure it out from there, or do we just collect some flow information on the library side in a flow matrix, and send it over periodically? We could do the first, as we intended originally, but this might require altering the structure of specific event types (acquire, for example). (Or, we could have the acquire event be a logged event that is dedicated to this exact feature.)

**Comment by gerazo** [comment]
What do you think about this plan @baselqyqony @BenBlaise @ip1996 @Hossam-Abdin ?

```
include:

Profiler
 - Profiler(dest_url=nullptr, buffer_size, aggregation_time)  // nullptr for no logging
 - Flush()  // flush buffer
 - Gather()  // force collection of data
 - GatherNFlush()
 - impl_

Scheduler
 - ...
 - Scheduler(..., profiler=Profiler())

Channel
 - ...
 - Log(event_name, event_value)


src:

ProfilerImpl
 - ???
 - logger_thread_  // gather periodically, send on full buffer with UDP
 - profile_aggregates_
 - send_buffer_

ProfileAggregate
 - ProfileAggregate(name)  // channel_name
 - Log(event_name, event_value)
 - name_
 - [(event_name, log_count, log_interval, min, max, avg), ...]  // universal value_type? float maybe?
 - [top_sender, ...]  // top 3?

ChannelImpl
 - ...
 - profile_aggregate_

```

**Comment by gerazo** [comment]
And what we log internally from Channel by default:

- `Push()` pipeline-relative time (arrival time into buffer)
- `Execute()` or `Poll()` pipeline-relative time (processing starts time)
- `Acquire()` to `Push()` time (fill-up time)
- `Execute() start` to `Execute() exit` time (thread usage time)
- `Execute()`/`Poll()` to `Release()` time (read-out time)
- other various internal stats on `Scheduler`

**Comment by gerazo** [comment]
`ProfileAggregate` is probalby better named as `Profile` or `ProfileData`, while one single record in it is probably should be named `ValueAggregate` or `LogAggregate`

**Comment by gerazo** [comment]
In case of aggregating the senders, we have to handle this as an internal feature. The `Scheduler` will tag the thread with the sending Channel name before `Execute()` and `Acquire()` will register the sender. If `Acquire()` gets and untagged thread, this is an input to the pipeline.

Output thread does not matter as with
 - `PolledChannel`, `Poll()` will be called by an external thread
 - `ScheduledChannel`, there will be no further `Acquire()` call to register as the receiver

**Comment by baselqyqony** [comment]
Thank you, I will create list of events instead of logging one event , and I already made enum for events but as I see they are getting more data and I feel that it will be better if we create Event separate object so that the one measurements profile log will hold list of events and each one of them could hold its type and time

**Comment by gerazo** [comment]
Yes, that is what I wanted to call LogAggregate of ValueAggregate or maybe EventAggregate.

**Comment by baselqyqony** [comment]
ok thank you , I created new branch from master and I put my code on it MeasurementProfilingBranch , I tried to build it and its building with passing tests and no ERRORS , I will  put further code changes on it

**Comment by baselqyqony** [comment]
today I checked The branch and found that it starts to appear on different git path , I dont know the reason my commits are going to this repo path 
https://github.com/baselqyqony/pipert/commits/MeasurementProfilingBranch

**Comment by gerazo** [comment]
Finished, entered into the experimentation phase.
